### ISSUE TITLE
Independence optimization

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril-classic#232]
## Description
Add independence-optimization for constraint solving. 
When a state with constraint set C needs to add a new constraint c’, instead of passing C ∧ c’ to the constraint solver to test satisfiability, pass R(C, c’) ∧ c’ where the expression R(C, c’)  returns only the constraints in C that have symbolic variables also in c’.

### Benefits
This optimization reduces the difficulty of the query and also increases constraint cache hits.

**Comment by norhh** [comment]
R(C, c') should also return constraints in C with variables related to the variables in c' right?
If thats the case this is how it should be:- 
G be graph with variables as nodes and edge (u, v) between variables u, v exists when there exists a constraint in C which has both the variables u, v.
R(C, c') = return constraints in C which has at least 1(more will belong automatically) variable belonging to a connected component in G such that there exists a variable in that connected component which is also in c'.

**Comment by JoranHonig** [comment]
@norhh yeah, R should also account for "transitive" dependence

**Comment by norhh** [comment]
This depends on callback refactor after that we can add a solver per each branch and then this should be done. One reason is because there might be some other set of constraints which aren't transitive dependent but are unsatisfiable, making the entire equation unsat, 
Also tried a prototype which eliminated non transitive constraints which resulted in slowing down of mythril by many folds.
