### ISSUE TITLE
Update issue descriptions

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#628]
## Description

Update the first line of issue descriptions to remove references to function name and create more reasonable output in the current truffle+analyze and Guardrails prototypes. Specifically, remote references to the function name and shorten the descriptions:

**suicide module:**

"A reachable SUICIDE instruction was detected."

**integer module:**

Overflow:

"The arithmetic operation can result in integer overflow."

Underflow:

"The subtraction can result in an integer underflow."

**ether_send module:**

"A non-zero amount of Ether is sent to a user-supplied address."

**Comment by rocky** [comment]
One thing to keep in mind for error messages in general. Some report formats like eslint's "stylish" (the default format for a number of reports), are limited in space: all information has to appear on a single line.

Here is a suggestion that I hope we discuss in conjunction with the "standard" issue format thing. Separate a warning into a Summary, followed by whatever elaboration is needed. However now that we have SWC numbers and detailed information about that, do not include any generic information, but leave that for the SWC to explain that. 

This is sort of like a news story: you give the short piece of information in the first sentence. And in the rest of the story you give the elaboration.

So a suggestion is that instead of: 

> The arithmetic operation can result in integer overflow."

It be: 

> A _name-of-operation_ can result in integer overflow

where _name-of-operation_ is "add", "multiply", or "exponentiation"

**Comment by b-mueller** [comment]
Sure, makes sense. I'll move these suggestions to the Maestro board.
